#!/usr/bin/lua
local ok=pcall(function()
    if arg[1]=="disable" then
        local backend=require "luci.model.ocserv_easy.backend"
        backend.action({action="guard",command="disable",revision=backend.data().revision})
    else require("luci.model.ocserv_easy.guard").work(arg[1]=="boot") end
end)
os.exit(ok and 0 or 1)
